// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIGsFGHF2usPa7frbYquB0gKXFXuYCdq8',
    appId: '1:344857300074:web:2f171db2d012f504b20e13',
    messagingSenderId: '344857300074',
    projectId: 'flutter-dr-ddae8',
    authDomain: 'flutter-dr-ddae8.firebaseapp.com',
    storageBucket: 'flutter-dr-ddae8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZXwW68w-VvuhN73V6XuosPn0GzRC55M',
    appId: '1:344857300074:android:1c369ae4a91e822bb20e13',
    messagingSenderId: '344857300074',
    projectId: 'flutter-dr-ddae8',
    storageBucket: 'flutter-dr-ddae8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrxCeX2kSpC4KGHSE-MWY7NFhmHe-zkFM',
    appId: '1:344857300074:ios:29d4bc4759ec74c2b20e13',
    messagingSenderId: '344857300074',
    projectId: 'flutter-dr-ddae8',
    storageBucket: 'flutter-dr-ddae8.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrxCeX2kSpC4KGHSE-MWY7NFhmHe-zkFM',
    appId: '1:344857300074:ios:29d4bc4759ec74c2b20e13',
    messagingSenderId: '344857300074',
    projectId: 'flutter-dr-ddae8',
    storageBucket: 'flutter-dr-ddae8.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIGsFGHF2usPa7frbYquB0gKXFXuYCdq8',
    appId: '1:344857300074:web:3c9af2f52ae4fc19b20e13',
    messagingSenderId: '344857300074',
    projectId: 'flutter-dr-ddae8',
    authDomain: 'flutter-dr-ddae8.firebaseapp.com',
    storageBucket: 'flutter-dr-ddae8.appspot.com',
  );
}
